apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyrax.fullname" . }}-env
  labels:
    app.kubernetes.io/name: {{ include "hyrax.name" . }}
    helm.sh/chart: {{ include "hyrax.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if .Values.postgresql.enabled }}
  DB_HOST: {{ template "hyrax.postgresql.fullname" . }}
  DB_PORT: "5432"
  {{- end }}
  {{- if .Values.memcached.enabled }}
  MEMCACHED_HOST: {{ template "hyrax.memcached.fullname" . }}
  {{- end }}
  RACK_ENV: production
  RAILS_ENV: production
  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{ template "hyrax.redis.fullname" . }}-master
  {{- end }}
  FCREPO_HOST: {{ template "hyrax.fcrepo.host" . }}
  FCREPO_PORT: {{ .Values.fcrepo.servicePort | default 8080 | quote }}
  FCREPO_REST_PATH: {{ .Values.fcrepo.restPath | default "fcrepo/rest" }}
  SOLR_ADMIN_USER: {{ template "hyrax.solr.username" . }}
  SOLR_ADMIN_PASSWORD: {{ template "hyrax.solr.password" . }}
  SOLR_COLLECTION_NAME: {{ template "hyrax.solr.collectionName" . }}
  SOLR_CONFIGSET_NAME: {{ template "hyrax.fullname" . }}
  SOLR_HOST: {{ template "hyrax.solr.host" . }}
  SOLR_PORT: "8983"
  SOLR_URL: {{ template "hyrax.solr.url" . }}
