apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyrax.fullname" . }}-worker
  labels:
    {{- include "hyrax.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "hyrax.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "hyrax.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: db-wait
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "hyrax.fullname" . }}-env
            - secretRef:
                name: {{ template "hyrax.fullname" . }}
          command:
            - sh
            - -c
            - db-wait.sh "$DB_HOST:$DB_PORT"
            - db-wait.sh "$FCREPO_HOST:$FCREPO_PORT"
            - db-wait.sh "$SOLR_HOST:$SOLR_PORT"
      serviceAccountName: {{ include "hyrax.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "hyrax.fullname" . }}-env
            - secretRef:
                name: {{ template "hyrax.fullname" . }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
