apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyrax.fullname" . }}
  labels:
{{ include "hyrax.labels" . | indent 4 }}
type: Opaque
data:
  SECRET_KEY_BASE: {{ randAlphaNum 20 | b64enc | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s/%s?pool=5" ( include "hyrax.postgresql.username" . ) ( include "hyrax.postgresql.password" . ) ( include "hyrax.postgresql.host" . ) ( include "hyrax.postgresql.database" . ) | b64enc }}
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.password }}
  {{- end }}
