{{- if and .Values.uploadsVolume.enabled (not .Values.uploadsVolume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "hyrax.fullname" . }}-uploads
  labels:
    {{- include "hyrax.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.uploadsVolume.size }}
{{- end }}
