version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.2'
      cache_version:
        type: string
        default: '1-2.x'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hyrax
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

  lint:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      cache_version:
        type: string
        default: '1-2.x'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    steps:
      - attach_workspace:
          at: ~/
      - samvera/rubocop

  build:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.2'
      cache_version:
        type: string
        default: '1-2.x'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test
    steps:
      - attach_workspace:
          at: ~/
      - samvera/engine_cart_generate:
          cache_key: v<< parameters.cache_version >>--internal-test-app-{{ checksum "hyrax.gemspec" }}-{{ checksum "spec/test_app_templates/lib/generators/test_app_generator.rb" }}-{{ checksum "lib/generators/hyrax/install_generator.rb" }}-<< parameters.rails_version >>-<< parameters.ruby_version >>
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          cache_version: << parameters.cache_version >>
          project: hyrax
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

  test:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
      cache_version:
        type: string
        default: '1-2.x'
    executor:
      name: 'samvera/ruby_fcrepo_solr_redis'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    parallelism: 10
    environment:
      COVERALLS_PARALLEL: true
    steps:
      - attach_workspace:
          at: ~/
      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/config
      # Rerun bundler in case this is a different ruby version than bundle and build steps
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          cache_version: << parameters.cache_version >>
          project: hyrax
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - bundle:
          ruby_version: "2.5.5"
          rails_version: "5.1.7"
          cache_version: "1-2.x"
      - lint:
          ruby_version: "2.5.5"
          cache_version: "1-2.x"
          requires:
            - bundle
      - build:
          ruby_version: "2.5.5"
          rails_version: "5.1.7"
          cache_version: "1-2.x"
          requires:
            - bundle
      - test:
          name: "ruby2-5-5"
          ruby_version: "2.5.5"
          requires:
            - build
            - lint
      - test:
          name: "ruby2-6-2"
          ruby_version: "2.6.2"
          cache_version: "1-2.x"
          requires:
            - build
            - lint
