version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.2'
    executor:
      name: 'samvera/ruby_fcrepo_solr_redis'
      ruby_version: << parameters.ruby_version >>

    resource_class: medium+
    working_directory: ~/hyrax
    parallelism: 10
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test
      COVERALLS_PARALLEL: true

    steps:
      - samvera/cached_checkout

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hyrax

      - samvera/engine_cart_generate:
          cache_key: v1-internal-test-app-{{ checksum "hyrax.gemspec" }}-{{ checksum "spec/test_app_templates/lib/generators/test_app_generator.rb" }}-{{ checksum "lib/generators/hyrax/install_generator.rb" }}-<< parameters.rails_version >>-<< parameters.ruby_version >>

      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/config

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hyrax

      - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_and_test:
          name: "ruby2-5-5_rails5-1"
          ruby_version: "2.5.5"
          rails_version: "5.1.7"
      - bundle_and_test:
          name: "ruby2-6-2_rails5-1"
          ruby_version: "2.6.2"
          rails_version: "5.1.7"
