version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.5.8
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.2'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hyrax
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

  lint:
    parameters:
      ruby_version:
        type: string
        default: 2.5.8
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    steps:
      - attach_workspace:
          at: ~/
      - samvera/rubocop

  build:
    parameters:
      ruby_version:
        type: string
        default: 2.5.8
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.2'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-keeps --skip-test --skip-bootsnap
    steps:
      - attach_workspace:
          at: ~/
      - samvera/engine_cart_generate:
          cache_key: v1-internal-test-app-jnf1-{{ checksum "hyrax.gemspec" }}-{{ checksum ".regen" }}-<< parameters.rails_version >>-<< parameters.ruby_version >>
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hyrax
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

  test:
    parameters:
      ruby_version:
        type: string
        default: 2.5.8
      bundler_version:
        type: string
        default: 1.17.3
      hyrax_valkyrie:
        type: string
        default: "false"
    executor:
      name: 'samvera/ruby_fcrepo_solr_redis_postgres'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    parallelism: 10
    environment:
      HYRAX_VALKYRIE: << parameters.hyrax_valkyrie >>
      VALKYRIE_SOLR_PORT: 8985
    steps:
      - attach_workspace:
          at: ~/
      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/conf
      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/conf
          core_name: hyrax-valkyrie-test
      # Rerun bundler in case this is a different ruby version than bundle and build steps
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hyrax
      - samvera/parallel_rspec

workflows:
  version: 2
  ruby2-5-8:
    jobs:
      - bundle:
          ruby_version: "2.5.8"
          rails_version: "5.2.4.3"
      - build:
          ruby_version: "2.5.8"
          rails_version: "5.2.4.3"
          requires:
            - bundle
      - test:
          name: "ruby2-5-8"
          ruby_version: "2.5.8"
          requires:
            - build
  ruby2-6-6:
    jobs:
      - bundle:
          ruby_version: "2.6.6"
          rails_version: "5.2.4.3"
      - build:
          ruby_version: "2.6.6"
          rails_version: "5.2.4.3"
          requires:
            - bundle
      - test:
          name: "ruby2-6-6"
          ruby_version: "2.6.6"
          requires:
            - build
      - test:
          name: "ruby2-6-6-valkyrie"
          ruby_version: "2.6.6"
          hyrax_valkyrie: "true"
          requires:
            - build
  ruby2-7-1:
    jobs:
      - bundle:
          ruby_version: "2.7.1"
          rails_version: "5.2.4.3"
          bundler_version: "2.1.4"
      - lint:
          ruby_version: "2.7.1"
          requires:
            - bundle
      - build:
          ruby_version: "2.7.1"
          rails_version: "5.2.4.3"
          bundler_version: "2.1.4"
          requires:
            - bundle
      - test:
          name: "ruby2-7-1"
          ruby_version: "2.7.1"
          bundler_version: "2.1.4"
          requires:
            - build
            - lint
