version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.5.8
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.4.3'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          cache_version: '{{ checksum ".regen" }}'
          project: hyrax
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

  lint:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    steps:
      - attach_workspace:
          at: ~/
      - samvera/rubocop

  build:
    parameters:
      ruby_version:
        type: string
        default: 2.5.8
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.4.3'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test
    steps:
      - attach_workspace:
          at: ~/
      - samvera/engine_cart_generate:
          cache_key: v1-2.x-internal-test-app-{{ checksum "hyrax.gemspec" }}-{{ checksum ".regen" }}-<< parameters.rails_version >>-<< parameters.ruby_version >>
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          cache_version: '{{ checksum ".regen" }}'
          project: hyrax
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

  test:
    parameters:
      ruby_version:
        type: string
        default: 2.5.8
      bundler_version:
        type: string
        default: 1.17.3
    executor:
      name: 'samvera/ruby_fcrepo_solr_redis'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    parallelism: 10
    environment:
      COVERALLS_PARALLEL: true
    steps:
      - attach_workspace:
          at: ~/
      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/config
      # Rerun bundler in case this is a different ruby version than bundle and build steps
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          cache_version: '{{ checksum ".regen" }}'
          project: hyrax
      - samvera/parallel_rspec

workflows:
  version: 2
  ruby2-5rails5-1:
    jobs:
      - bundle:
          ruby_version: "2.5.8"
          rails_version: "5.1.7"
      - lint:
          ruby_version: "2.5.8"
          requires:
            - bundle
      - build:
          ruby_version: "2.5.8"
          rails_version: "5.1.7"
          requires:
            - bundle
      - test:
          name: "rails5-1"
          ruby_version: "2.5.8"
          requires:
            - build
  ruby2-5rails5-2:
    jobs:
      - bundle:
          ruby_version: "2.5.8"
          rails_version: "5.2.4.3"
      - build:
          ruby_version: "2.5.8"
          rails_version: "5.2.4.3"
          requires:
            - bundle
      - lint:
          ruby_version: "2.5.8"
          requires:
            - bundle
      - test:
          name: "ruby2-5-8"
          ruby_version: "2.5.8"
          requires:
            - build
  ruby2-6rails5-2:
    jobs:
      - bundle:
          ruby_version: "2.6.6"
          rails_version: "5.2.4.3"
      - build:
          ruby_version: "2.6.6"
          rails_version: "5.2.4.3"
          requires:
            - bundle
      - lint:
          ruby_version: "2.6.6"
          requires:
            - bundle
      - test:
          name: "ruby2-6-6"
          ruby_version: "2.6.6"
          requires:
            - build
            - lint
  ruby2-7rails5-2:
    jobs:
      - bundle:
          ruby_version: "2.7.1"
          rails_version: "5.2.4.3"
      - build:
          ruby_version: "2.7.1"
          rails_version: "5.2.4.3"
          requires:
            - bundle
      - lint:
          ruby_version: "2.7.1"
          requires:
            - bundle
      - test:
          name: "ruby2-7-1"
          ruby_version: "2.7.1"
          requires:
            - build
            - lint
