version: 2.1
executors:
  ruby:
    docker:
      - image: circleci/ruby:2.5.3
    resource_class: small
    working_directory: ~/hyrax
    environment: &spec_env
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 16
      BUNDLE_RETRY: 3
      RAILS_ENV: test
      RAILS_VERSION: << parameters.rails_version >>
      RACK_ENV: test
      FCREPO_TEST_PORT: 8080/fcrepo
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test
      SPEC_OPTS: --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      COVERALLS_PARALLEL: true

orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
        default: '5.2.2'
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    docker:
    - image: circleci/ruby:2.5.3-node-browsers-legacy
    - image: circleci/redis:4
    - image: ualbertalib/docker-fcrepo4:4.7
      environment:
        CATALINA_OPTS: "-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server -Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+DisableExplicitGC"
    - image: solr:7-alpine
      command: bin/solr -cloud -noprompt -f -p 8985

    resource_class: medium+
    working_directory: ~/hyrax
    parallelism: 10
    environment: *spec_env
    steps:
      - samvera/cached_checkout

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hyrax

      - samvera/engine_cart_generate:
          cache_key: v1-internal-test-app-{{ checksum "hyrax.gemspec" }}-{{ checksum "spec/test_app_templates/lib/generators/test_app_generator.rb" }}-{{ checksum "lib/generators/hyrax/install_generator.rb" }}-<< parameters.rails_version >>-<< parameters.ruby_version >>

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hyrax

      - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_and_test:
          name: "ruby2-5-5_rails5-1"
          ruby_version: "2.5.5"
          rails_version: "5.1.7"
      - bundle_and_test:
          name: "ruby2-6-2_rails5-1"
          ruby_version: "2.6.2"
          rails_version: "5.1.7"
