attributes:
  title:
    type: string
    multiple: true
    index_keys:
      - "title_sim"
      - "title_tesim"
  date_modified:
    type: date_time
  date_uploaded:
    type: date_time
  depositor:
    type: string
