apiVersion: v2
name: hyrax
description: An open-source, Samvera-powered digital repository system
type: application
version: 0.9.0
appVersion: 3.0.1
dependencies:
  - name: fcrepo
    version: 0.6.0
    repository: https://samvera-labs.github.com/fcrepo-charts
    condition: fcrepo.enabled
  - name: memcached
    version: 4.2.21
    repository: https://charts.bitnami.com/bitnami
    condition: memcached.enabled
  - name: postgresql
    version: 10.3.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 10.7.16
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: solr
    version: 0.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: solr.enabled
